// src/About.tsx
import { Box, Typography } from "@mui/material";

function About() {
  return (
    <Box>
      <Typography
        sx={{
          pl: "10%",
          fontSize: { xs: "8vw", sm: "3vw" },
          fontFamily: "Russo One",
        }}
        gutterBottom
      >
        O MNĚ
      </Typography>
      <Typography
        sx={{
          px: "10%",
          fontSize: { xs: "4vw", sm: "2vw", md: "1.5vw", lg: "1.2vw" },
          fontFamily: "Russo One",
        }}
        gutterBottom
      >
        Ahoj! Jmenuju se Michal Zbranek. Portfolio jsem si vytvořil z toho
        důvodu, abych mohl ukázat všechny projekty, které jsem vytvářel v
        Reactu. Vystudoval jsem Fakultu Informatiky v Brně a nyní bydlím ve
        Zlíně. Pracuju v Koale42 na pozici Testera a snažím se dostat na pozici
        Developera.
      </Typography>
    </Box>
  );
}

export default About;

// src/components/About.vue
<template>
  <img id="about" src="../assets/cropped.jpg" style="width: 25vw;">
  <h1 class="fw-bold" style="position: absolute; top: 25vw;">o mně</h1>
  <p style="width: 40vw; top: 35vw; position: absolute;">
    Čauko! Jmenuju se Michal Zbranek.
    Portfolio jsem si vytvořil z toho důvodu, abych se trochu seznámil s frameworkem VUE a měl mé různé koníčky pohromadě.
    Mezi odkazy například najdete i mé kreslení a vlastní blog.
    Vystudoval jsem Fakultu Informatiky v Brně a nyní bydlím ve Zlíně s přítelkyní.
    Pracuju v Tietu na pozici Testera/Developera a nyní se k tomu snažím naučit tvorbu webových stránek.
    Do toho miluji sport a filmy/seriály.
  </p>
  <img src="../assets/cropped_snow.jpg" style="width: 25vw; right: 0; position: absolute;">
  <img src="../assets/cropped_sea.jpg" style="width: 15vw; right: 22.5vw; top: 10vw; position: absolute;">
</template>

<style>
img {
  border-radius: 3%;
}
</style>
